### ISSUE TITLE
css of date changed by dubizzle

### ISSUE THREAD

**Issue by ninjatrench** [aksiksi/dubizzle#3]
Programs crashes due to un-handled exception caused by change of design in host site.
as '.date' attribute has been removed which is used in this code to parse date

file : uae.py
line : 150
Stacktrace : 
IndexError   Traceback (most recent call last)
<ipython-input-169-4279d50ce515> in <module>()
----> result.select('.date')[0].text.strip()
IndexError: list index out of range

WorkAround : 
Change Line number 150:
u'date': parse_date(result.select('.date')[0].text.strip()),
to :
u'date': parse_date(result.select('.listing-details-header')[0].text.strip())

**Comment by aksiksi** [comment]
Thanks for the update. Firstly, it would have been better if you replied to the original issue. Secondly, the proper way to submit a fix is to make a **pull request**.

Why should you submit a PR (pull request)? So you can get credit for the fix. How to make a PR? Easy.
1. [Fork](https://github.com/Cyph0n/dubizzle/fork) the repo.
2. Test the change and make sure it works as expected.
3. Make the change you want on Github and commit it.
4. Once your repo is ahead of this one, you'll see the option to submit a pull request. Do that.

If your fix works as expected, I will accept your request, and your change will be merged into this repo.
